name: mnale_client
description: A simple ecommerce site called Mnale

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  connectivity: ^3.0.6
  http: ^0.13.4
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
